import express from 'express';
import { getPosts, getPostBySlug, createPost, updatePost, deletePost } from '../controllers/post.controller.js';
import { protect, adminOnly } from '../middleware/auth.middleware.js';
const router = express.Router();
router.get('/', getPosts);
router.get('/:slug', getPostBySlug);
router.post('/', protect, adminOnly, createPost);
router.put('/:id', protect, adminOnly, updatePost);
router.delete('/:id', protect, adminOnly, deletePost);
export default router;